import {
  HomePage,
  Integrity,
  Contact,
  DefaultLayout,
  AreasServed,
  BuildingProcess,
  FloorPlans,
  InspirationalGallery,
  ServiceRequestForm,
  BuildersTrend,
  WarantyInformation,
  CommunityLinks,
  Testimonials,
  AboutAviarBuilders,
  RecomenedPartner,
  Subdivisions,
  FrequentlyAskedQuestions,
  CustomConstruction,
  RemodellingServices,
  RealEstateBrokage,
  HomeForSales,
  LotsForSale,
  ComersialConstruction,
  OurHomes,
  ClientValueCreation,
  // OurWebsites,
  // Remodelprojects,
} from "./Lazy";

const buildersRoutes = [
  { path: "/abs/homepage", exact: true, name: "HomePage", publiclayout: true, component: HomePage },
  { path: "/contact", exact: true, name: "Contact", publiclayout: true, component: Contact },
  { path: "/abs/integrity", exact: true, name: "Integrity", publiclayout: true, component: Integrity },
  { path: "/abs/client-value-creation", exact: true, name: "ClientValueCreation", publiclayout: true, component: ClientValueCreation },
  { path: "/abs/aboutUs/areasserved", exact: true, name: "AreasServed", publiclayout: true, component: AreasServed },
  { path: "/abs/aboutUs/buildingprocess", exact: true, name: "BuildingProcess", publiclayout: true, component: BuildingProcess },
  { path: "/abs/floorplans", exact: true, name: "FloorPlans", publiclayout: true, component: FloorPlans },
  { path: "/photogallery/inspirationalgallery", exact: true, name: "InspirationalGallery", publiclayout: true, component: InspirationalGallery },
  { path: "/photogallery/ourhomes", exact: true, name: "OurHomes", publiclayout: true, component: OurHomes },
  { path: "/resources/servicerequestform", exact: true, name: "ServiceRequestForm", publiclayout: true, component: ServiceRequestForm },
  { path: "/resources/builderstrend", exact: true, name: "BuildersTrend", publiclayout: true, component: BuildersTrend },
  { path: "/resources/recommendedpartners", exact: true, name: "RecomenedPartner", publiclayout: true, component: RecomenedPartner },
  { path: "/resources/frequentlyaskedquestions", exact: true, name: "FrequentlyAskedQuestions", publiclayout: true, component: FrequentlyAskedQuestions },
  { path: "/resources/subdivisions", exact: true, name: "Subdivisions", publiclayout: true, component: Subdivisions },
  { path: "/resources/warantyinformation", exact: true, name: "WarantyInformation", publiclayout: true, component: WarantyInformation },
  { path: "/resources/communitylinks", exact: true, name: "CommunityLinks", publiclayout: true, component: CommunityLinks },
  { path: "/aboutus/testimonials", exact: true, name: "Testimonials", publiclayout: true, component: Testimonials },
  { path: "/aboutus/about-aviar-builders", exact: true, name: "AboutAviarBuilders", publiclayout: true, component: AboutAviarBuilders },
  { path: "/abs/services/customconstruction", exact: true, name: "CustomConstruction", publiclayout: true, component: CustomConstruction },
  { path: "/services/remodellingservices", exact: true, name: "RemodellingServices", publiclayout: true, component: RemodellingServices },
  { path: "/services/realestatebrokage", exact: true, name: "RealEstateBrokage", publiclayout: true, component: RealEstateBrokage },
  { path: "/abs/services/comersialconstruction", exact: true, name: "ComersialConstruction", publiclayout: true, component: ComersialConstruction },
  { path: "/forsale/homes-for-sale", exact: true, name: "HomeForSales", publiclayout: true, component: HomeForSales },
  { path: "/forsale/lots-for-sale", exact: true, name: "LotsForSale", publiclayout: true, component: LotsForSale },
  // { path: "/photogallery/remoteProjects", exact: true, name: "Remodelprojects", component: Remodelprojects },
  // { path: "*", name: "NotFoundPage", component: NotFoundPage },
];

export default buildersRoutes;
